// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileBase64() {
  return window['go']['main']['App']['GetFileBase64']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}
