// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileBase64():Promise<string>;

export function GetStatus():Promise<number>;
