name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - platform: 'linux/amd64'
            os: 'ubuntu-latest'
            hint: 'linux-amd64'
            ext: ''
          - platform: 'linux/arm64'
            os: 'ubuntu-24.04-arm'
            hint: 'linux-arm64'
            ext: ''
          - platform: 'windows/amd64'
            os: 'windows-latest'
            hint: 'windows-amd64.exe'
            ext: ''
          - platform: 'windows/arm64'
            os: 'windows-11-arm'
            hint: 'windows-arm64.exe'
            ext: ''
          - platform: 'darwin/universal'
            os: 'macos-latest'
            hint: 'darwin-universal.app.zip'
            ext: '.app.zip'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: "chalaoshi"
          build-platform: ${{ matrix.build.platform }}
          package: false

      - name: Build server
        run: |
          cd server
          go build -o ../build/chalaoshi-server-${{ matrix.build.hint }}
          cd ..

      # rename the output file to match the platform
      - name: Rename output file
        run: |
          mv "build/bin/chalaoshi${{ matrix.build.ext }}" "build/chalaoshi-client-${{ matrix.build.hint }}"

      # upload to the tag release
      - uses: actions/upload-artifact@v4
        with:
          name: Wails Build chalaoshi-client-${{ matrix.build.hint }}
          path: |
            build/chalaoshi-client-${{ matrix.build.hint }}
            build/chalaoshi-server-${{ matrix.build.hint }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/chalaoshi-client-${{ matrix.build.hint }}
            build/chalaoshi-server-${{ matrix.build.hint }}
